[package]
name = "egui_sdl2_test"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.27.2"

[build-dependencies]
cbindgen = "0.26.0"
cmake = "0.1.50"
