[package]
name = "egui_sdl2_gl_cube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stb_image = "*"
nalgebra-glm = "*"

[dependencies.egui_sdl2_gl]
version = "*"
default-features = true
